### PR TITLE
Made code compatible with PHP 5.3

### LINKED ISSUE #3: Customer completed order email is sent in the wrong language
Submitted in two places by https://wordpress.org/support/profile/og-s:
https://wordpress.org/support/topic/woocommerce-emails-3
https://wordpress.org/support/topic/wrong-email-language

The description copied here:

I'm using the latest version of Github qTranslate-X, WooCommerce & qTranslate-X

The customer processing order email is sent in the correct language. But than, all e-mails sent from the woocommerce admin are sent in the wrong language. The customer completed order email is sent in the wrong language. It seems that the default language is used.

### PR DESCRIPTION
**Pull request by mweimerskirch**
Made code compatible with PHP 5.3 -.-
Fixes #3

### CODE REVIEW

**Comment by mweimerskirch** [comment]
Do we have to support 5.3? The official WordPress requirements say 5.4: https://wordpress.org/about/requirements/

**Comment by johnclause** [comment]
> Do we have to support 5.3?

I would try to not to be fancy, because I would assume that there are many servers in the world, which are still behind ...

**Comment by mweimerskirch** [comment]
I'm just not used to write code for 2009 anymore ;-)
But yes, you're right :-(

**Comment by OGSWEB** [comment]
Sorry, my client has other scripts and websites on the same plateform...

**Comment by OGSWEB** [comment]
Is it the correct code for 5.2?

add_action( 'save_post', 'qwc_my_function', 10, 3);
function qwc_my_function($post_id, $post, $update)
 {
    if ( 'shop_order' != $post->post_type || $update /\* ignore updates */ ) {
        return;
    }
    global $q_config;
    add_post_meta( $post_id, '_user_language', $q_config['language'], true );
};

**Pull request merged**
